# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gyunyu 0.3.3 ruby lib

Gem::Specification.new do |s|
  s.name = "gyunyu"
  s.version = "0.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["wtnabe"]
  s.date = "2015-02-27"
  s.description = "now available export command"
  s.email = "wtnabe@gmail.com"
  s.executables = ["gyunyu"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/gyunyu",
    "gyunyu.gemspec",
    "lib/gyunyu.rb",
    "lib/gyunyu/app.rb",
    "lib/gyunyu/command.rb",
    "lib/gyunyu/command/export/app.rb",
    "lib/gyunyu/command/export/custom_filter.rb",
    "lib/gyunyu/command/export/format/csv.rb",
    "lib/gyunyu/command/export/format/json.rb",
    "lib/gyunyu/command/export/format/yaml.rb",
    "lib/gyunyu/command/export/option.rb",
    "lib/gyunyu/command/export/total_estimate.rb",
    "lib/gyunyu/expander.rb",
    "lib/gyunyu/token.rb",
    "spec/app/.gitkeep",
    "spec/app/command/export/app_spec.rb",
    "spec/app/command/export/custom_filter_spec.rb",
    "spec/app/command/export/format/csv_spec.rb",
    "spec/app/command/export/option_spec.rb",
    "spec/app/command/export/total_estimate_spec.rb",
    "spec/app/command_spec.rb",
    "spec/app/expander_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/app_export.rb",
    "spec/support/task_raw_data.rb",
    "spec/token/token_spec.rb",
    "tasks/git.rake",
    "tasks/spec.rake",
    "tmp/.gitkeep"
  ]
  s.homepage = "http://github.com/wtnabe/gyunyu"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Simple RTM app for CLI"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rtmilk>, ["~> 0.3"])
      s.add_runtime_dependency(%q<xml-simple>, [">= 0"])
      s.add_runtime_dependency(%q<rtm-time>, [">= 0.2.0"])
      s.add_development_dependency(%q<rspec>, ["> 2"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rr>, [">= 0"])
    else
      s.add_dependency(%q<rtmilk>, ["~> 0.3"])
      s.add_dependency(%q<xml-simple>, [">= 0"])
      s.add_dependency(%q<rtm-time>, [">= 0.2.0"])
      s.add_dependency(%q<rspec>, ["> 2"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rr>, [">= 0"])
    end
  else
    s.add_dependency(%q<rtmilk>, ["~> 0.3"])
    s.add_dependency(%q<xml-simple>, [">= 0"])
    s.add_dependency(%q<rtm-time>, [">= 0.2.0"])
    s.add_dependency(%q<rspec>, ["> 2"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rr>, [">= 0"])
  end
end

